/**
 * Demo persona — plan §16.5. "Boulangerie Chartier": a French bakery whose flour line IS wheat.
 *
 * The canonical ledger is generated by Sara's sector-calibrated treasury case generator in
 * `yield-forecasting` (commit `bcbdeca`) — the lead magnet literally seeds the hackathon demo.
 * These constants pin the shape; the generator fills the daily ledger from a FIXED seed so the
 * scenario driver replays bit-identically for the video.
 *
 * Amounts are USDC base units as strings (decimals per ARC_NATIVE_DECIMALS). Placeholder magnitudes
 * below are human-readable EUR figures from the plan; convert to base units when wiring the generator.
 */
export const BOULANGERIE_CHARTIER = {
  name: 'Boulangerie Chartier',
  averageBalanceEur: 38_000,
  payrollEur: 12_000, // paid on the 28th
  payrollDayOfMonth: 28,
  urssafDayOfMonth: 5,
  rentDayOfMonth: 1,
  flourCostSharePct: 14, // the exposure leg: flour ≈ 14% of costs, and flour IS wheat
  seasonalRevenue: true,
  /** Fixed RNG seed — the scenario MUST be deterministic (video + offline-demo fallback). */
  seed: 20260714,
} as const;
